name: AgentManagerX
options:
  bundleIdPrefix: com.madda
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.9"
targets:
  AgentManagerX:
    type: application
    platform: macOS
    sources:
      - path: App/Sources
      - path: App/Resources
        buildPhase: resources
        excludes:
          - native-mini-viewer/MiniViewer.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.madda.agentmanagerx
        PRODUCT_NAME: "Agent Manager X"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: "Agent Manager X"
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.productivity
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright (c) 2026"
        MARKETING_VERSION: 1.1
        CURRENT_PROJECT_VERSION: 1
schemes:
  AgentManagerX:
    build:
      targets:
        AgentManagerX: all
    run:
      config: Debug
