import Foundation

enum SettingsKeys {
    static let globalHotkey = "agent-manager-x-hotkey"
    static let miniViewerHotkey = "agent-manager-x-mini-viewer-hotkey"
    static let miniViewerSide = "agent-manager-x-mini-viewer-side"
    static let miniViewerShowOnActiveMonitor = "agent-manager-x-mini-viewer-show-on-active-monitor"
    static let miniViewerPinnedScreenTarget = "agent-manager-x-mini-viewer-pinned-screen-target"
    static let miniViewerPinnedScreenNameSnapshot = "agent-manager-x-mini-viewer-pinned-screen-name-snapshot"
    static let miniViewerShowOnStart = "agent-manager-x-mini-viewer-show-on-start"
    static let miniViewerShowRecentSessionsOnly = "agent-manager-x-mini-viewer-show-recent-sessions-only"
    static let miniViewerRecentActivityWindowMinutes = "agent-manager-x-mini-viewer-recent-activity-window-minutes"
    static let miniViewerMaxSessions = "agent-manager-x-mini-viewer-max-sessions"
    static let mainAppUIElementSize = "agent-manager-x-main-app-ui-element-size"
    static let miniViewerUIElementSize = "agent-manager-x-mini-viewer-ui-element-size"
    static let defaultEditor = "agent-manager-x-default-editor"
    static let customEditorCommand = "agent-manager-x-custom-editor-command"
    static let defaultTerminal = "agent-manager-x-default-terminal"
    static let customTerminalCommand = "agent-manager-x-custom-terminal-command"
    static let cardClickAction = "agent-manager-x-click-action"
    static let displayMode = "agent-manager-x-display-mode"
    static let sessionDetailsRetrievalMode = "agent-manager-x-session-details-retrieval-mode"
    static let useSlowerCompatibleProjectSwitching = "agent-manager-x-slower-compatible-project-switching"
    static let legacyExperimentalVSCodeSessionOpening = "agent-manager-x-expiremental-vs-code-session-opening"
    static let theme = "agent-manager-x-theme"
    static let backgroundImage = "agent-manager-x-background-image"
    static let overlayOpacity = "agent-manager-x-overlay-opacity"
    static let overlayColor = "agent-manager-x-overlay-color"
    static let notificationSound = "agent-manager-x-notification-sound"
    static let projectCommands = "agent-manager-x-project-commands"
    static let customNames = "agent-manager-x-custom-names"
    static let customURLs = "agent-manager-x-custom-urls"
    static let showSessionFilePath = "agent-manager-x-show-session-file-path"
}
